name: Backup all repos

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * * # Daily

permissions:
  contents: read

jobs:
  fetch-repos:
    name: Fetch repos
    runs-on: ubuntu-22.04

    outputs:
      track-repos: ${{ steps.fetch-track-repos.outputs.track-repos }}
      tooling-repos: ${{ steps.fetch-tooling-repos.outputs.tooling-repos }}
      other-repos: ${{ steps.fetch-other-repos.outputs.other-repos }}

    steps:
      - name: Fetch the track repos
        id: fetch-track-repos
        run: |
          track_repos=$(gh api -X GET --paginate search/repositories -f q='org:exercism is:public archived:false topic:exercism-track' --jq '[.items[] | .name]' | tr -d '\n')
          echo "track-repos=${track_repos}" >> "${GITHUB_OUTPUT}"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Fetch the tooling repos
        id: fetch-tooling-repos
        run: |
          tooling_repos=$(gh api -X GET --paginate search/repositories -f q='org:exercism is:public archived:false topic:exercism-tooling' --jq '[.items[] | .name]' | tr -d '\n')
          echo "tooling-repos=${tooling_repos}" >> "${GITHUB_OUTPUT}"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Fetch the other repos
        id: fetch-other-repos
        run: |
          other_repos=$(gh api -X GET --paginate search/repositories -f q='org:exercism is:public archived:false -topic:exercism-track -topic:exercism-tooling' --jq '[.items[] | .name]' | tr -d '\n')
          echo "other-repos=${other_repos}" >> "${GITHUB_OUTPUT}"
        env:
          GH_TOKEN: ${{ github.token }}

  backup-track-repos:
    needs: [fetch-repos]
    name: Backup

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        repo: ${{ fromJson(needs.fetch-repos.outputs.track-repos) }}

    uses: exercism/backup/.github/workflows/backup.yml@main
    secrets: inherit
    with:
      repo: ${{ matrix.repo }}

  backup-tooling-repos:
    needs: [fetch-repos]
    name: Backup

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        repo: ${{ fromJson(needs.fetch-repos.outputs.tooling-repos) }}

    uses: exercism/backup/.github/workflows/backup.yml@main
    secrets: inherit
    with:
      repo: ${{ matrix.repo }}

  backup-other-repos:
    needs: [fetch-repos]
    name: Backup

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        repo: ${{ fromJson(needs.fetch-repos.outputs.other-repos) }}

    uses: exercism/backup/.github/workflows/backup.yml@main
    secrets: inherit
    with:
      repo: ${{ matrix.repo }}
