name: Backup

on:
  workflow_call:
    inputs:
      repo:
        required: true
        description: The repo name (e.g. "prolog")
        type: string

permissions:
  contents: read

jobs:
  backup-repo:
    name: ${{ inputs.repo }}
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          repository: exercism/${{ inputs.repo }}
          fetch-depth: 0 # Fetch the entire history to backup everyting

      - name: Setup SSH for AWS CodeCommit
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_CODECOMMIT_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa git-codecommit.${{ secrets.AWS_REGION }}.amazonaws.com >> ~/.ssh/known_hosts

      - name: Push repo to AWS CodeCommit
        run: |
          git remote add aws-codecommit "ssh://${{ secrets.AWS_CODECOMMIT_SSH_PRIVATE_KEY_ID }}@git-codecommit.${{ secrets.AWS_REGION }}.amazonaws.com/v1/repos/${{ inputs.repo }}"
          git push aws-codecommit main
          git checkout $(git log --branches -1 --pretty=format:"%H")
          git branch -D main
          git push --tags --force --prune aws-codecommit "refs/remotes/origin/*:refs/heads/*"
