name: Backup repo
on:
  repository_dispatch:
    types: [backup_repo]
  workflow_dispatch:
    inputs:
      repo:
        description: The name of the repo to backup (e.g. 'configlet')
        required: false

permissions:
  contents: read

jobs:
  backup-repo:
    name: Backup repo
    uses: exercism/backup/.github/workflows/backup.yml@main
    secrets: inherit
    with:
      repo: ${{ github.event.inputs && github.event.inputs.repo || github.event.client_payload.repo }}
