name: Backup all repos

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * * # Daily

permissions:
  contents: read

jobs:
  fetch-repos:
    name: Fetch repos
    runs-on: ubuntu-22.04

    outputs:
      track-repos: ${{ steps.fetch-repos.outputs.track-repos }}
      tooling-repos: ${{ steps.fetch-repos.outputs.tooling-repos }}
      other-repos: ${{ steps.fetch-repos.outputs.other-repos }}

    steps:
      - name: Fetch the repos
        id: fetch-repos
        run: |
          track_repos=$(gh api -X GET --paginate search/repositories -f q='org:exercism is:public archived:false topic:exercism-track' --jq '[.items[] | .name]' | jq -c '.')
          tooling_repos=$(gh api -X GET --paginate search/repositories -f q='org:exercism is:public archived:false topic:exercism-tooling' --jq '[.items[] | .name]' | jq -c '.')
          other_repos=$(gh api -X GET --paginate search/repositories -f q='org:exercism is:public archived:false -topic:exercism-track -topic:exercism-tooling' --jq '[.items[] | .name]' | jq -c '.')

          echo "track-repos=${track_repos}" >> "$GITHUB_OUTPUT"
          echo "tooling-repos=${tooling_repos}" >> "$GITHUB_OUTPUT"
          echo "other-repos=${other_repos}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}

  backup-track-repos:
    needs: [fetch-repos]
    name: Backup ${{ matrix.repo }}

    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.fetch-repos.outputs.track-repos) }}

    uses: exercism/backup/.github/workflows/backup.yml@main
    secrets: inherit
    with:
      repo: ${{ matrix.repo }}

  backup-tooling-repos:
    needs: [fetch-repos]
    name: Backup ${{ matrix.repo }}

    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.fetch-repos.outputs.tooling-repos) }}

    uses: exercism/backup/.github/workflows/backup.yml@main
    secrets: inherit
    with:
      repo: ${{ matrix.repo }}

  backup-other-repos:
    needs: [fetch-repos]
    name: Backup ${{ matrix.repo }}

    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.fetch-repos.outputs.other-repos) }}

    uses: exercism/backup/.github/workflows/backup.yml@main
    secrets: inherit
    with:
      repo: ${{ matrix.repo }}
