name: Backup all repos

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * * # Daily

permissions:
  contents: read

jobs:
  fetch-repos:
    name: Fetch repos
    runs-on: ubuntu-22.04

    outputs:
      track-repos: ${{ steps.fetch-track-repos.outputs.repos }}
      tooling-repos: ${{ steps.fetch-tooling-repos.outputs.repos }}
      other-repos: ${{ steps.fetch-other-repos.outputs.repos }}

    steps:
      - name: Fetch the track repos
        id: fetch-track-repos
        run: |
          repos=$(gh api -X GET --paginate search/repositories -f q='org:exercism is:public archived:false topic:exercism-track' --jq '[.items[] | .name]')

          echo 'REPOS<<EOF' >> $GITHUB_ENV
          echo "repos=${repos}" >> "$GITHUB_OUTPUT"
          echo 'EOF' >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Fetch the tooling repos
        id: fetch-tooling-repos
        run: |
          repos=$(gh api -X GET --paginate search/repositories -f q='org:exercism is:public archived:false topic:exercism-tooling' --jq '[.items[] | .name]')

          echo 'REPOS<<EOF' >> $GITHUB_ENV
          echo "repos=${repos}" >> "$GITHUB_OUTPUT"
          echo 'EOF' >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Fetch the other repos
        id: fetch-other-repos
        run: |
          repos=$(gh api -X GET --paginate search/repositories -f q='org:exercism is:public archived:false -topic:exercism-track -topic:exercism-tooling' --jq '[.items[] | .name]')

          echo 'REPOS<<EOF' >> $GITHUB_ENV
          echo "repos=${repos}" >> "$GITHUB_OUTPUT"
          echo 'EOF' >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}

  backup-track-repos:
    needs: [fetch-repos]
    name: Backup ${{ matrix.repo }}

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        repo: ${{ fromJson(needs.fetch-repos.outputs.track-repos) }}

    uses: exercism/backup/.github/workflows/backup.yml@main
    secrets: inherit
    with:
      repo: ${{ matrix.repo }}

  backup-tooling-repos:
    needs: [fetch-repos]
    name: Backup ${{ matrix.repo }}

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        repo: ${{ fromJson(needs.fetch-repos.outputs.tooling-repos) }}

    uses: exercism/backup/.github/workflows/backup.yml@main
    secrets: inherit
    with:
      repo: ${{ matrix.repo }}

  backup-other-repos:
    needs: [fetch-repos]
    name: Backup ${{ matrix.repo }}

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        repo: ${{ fromJson(needs.fetch-repos.outputs.other-repos) }}

    uses: exercism/backup/.github/workflows/backup.yml@main
    secrets: inherit
    with:
      repo: ${{ matrix.repo }}
