name: Backup repo
on:
  repository_dispatch:
    types: [backup_repo]

permissions:
  contents: read

jobs:
  backup_repo:
    uses: exercism/backup/.github/workflows/backup.yml@main
    secrets: inherit
    with:
      repo: ${{ github.event.client_payload.repo }}
